apiVertsion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-example
  annotations:

spec:
  rules:
  - host:
    http:
      paths:
      - path:
        pathType:
        backend:
          service:
            name:
            port:
              number: